export const defaults = {
  state: 'WAITING',
  roundId: 1,
  endsAt: null as string | null,
  pausedAt: null as string | null,
  shopOpen: true,
  freezeFinalSeconds: 120,
  freezeLimitSeconds: 60,
  leaderboardDelaySeconds: 75,
  antiSniping: true,
  allowRematch: true,
  detailedAnalysis: false,
  individualQuestionPrice: 60,
  sessionRoleSelection: true,
  chessTimeControl: 'UNTIMED' as 'UNTIMED' | 'TIMED',
  chessBaseTimeSeconds: 600,
  chessIncrementSeconds: 10,
  scoring: {
    capture: { p: 10, n: 30, b: 30, r: 50, q: 90, k: 70 },
    result: { win: 100, draw: 50, loss: 10 },
    quality: { Excellent: 8, Good: 5, Accurate: 2, Inaccuracy: -1, Mistake: -3, Blunder: -5 },
    thresholds: [10, 30, 60, 100, 200],
    debugging: { Easy: 10, Medium: 20, Hard: 30, Expert: 50 },
    enableFarmingGuard: true,
    farmingGuardFirstNPlies: 12,
    earlyResignationGuard: true,
    earlyResignationPly: 15,
    engineDepth: 12,
    engineTimeMs: 250,
    maxBonus: 8,
    maxPenalty: 5,
    strategicResignPoints: 50,
  },
};
